#!/bin/sh
module="scull"
device="scull"

# invoke rmmod with all arguments we got
/sbin/rmmod $module $* || exit 1

# Remove stale nodes

rm -vf /dev/${device} /dev/${device}[0-3] 
rm -vf /dev/${device}priv
rm -vf /dev/${device}pipe /dev/${device}pipe[0-3]
rm -vf /dev/${device}single
rm -vf /dev/${device}uid
rm -vf /dev/${device}wuid





