#!/bin/sh
# $Id: scull_load,v 1.4 2004/11/03 06:19:49 rubini Exp $
module="scull"
device="scull"
mode="664"

# Group: since distributions do it differently, I used the group "adm"
group="adm"

# invoke insmod with all arguments we got
# and use a pathname, as insmod doesn't look in . by default
/sbin/insmod ./$module.ko $* || exit 1

# retrieve major number
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
echo $major

# Remove stale nodes and replace them, then give gid and perms
# Usually the script is shorter, it's scull that has several devices in it.

rm -vf /dev/${device}[0-3]
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
ln -svf ${device}0 /dev/${device}
chgrp -v $group /dev/${device}[0-3] 
chmod -v $mode  /dev/${device}[0-3]

rm -vf /dev/${device}pipe[0-3]
mknod /dev/${device}pipe0 c $major 4
mknod /dev/${device}pipe1 c $major 5
mknod /dev/${device}pipe2 c $major 6
mknod /dev/${device}pipe3 c $major 7
ln -svf ${device}pipe0 /dev/${device}pipe
chgrp -v $group /dev/${device}pipe[0-3] 
chmod -v $mode  /dev/${device}pipe[0-3]

rm -vf /dev/${device}single
mknod /dev/${device}single  c $major 8
chgrp -v $group /dev/${device}single
chmod -v $mode  /dev/${device}single

rm -vf /dev/${device}uid
mknod /dev/${device}uid   c $major 9
chgrp -v $group /dev/${device}uid
chmod -v $mode  /dev/${device}uid

rm -vf /dev/${device}wuid
mknod /dev/${device}wuid  c $major 10
chgrp -v $group /dev/${device}wuid
chmod -v $mode  /dev/${device}wuid

rm -vf /dev/${device}priv
mknod /dev/${device}priv  c $major 11
chgrp -v $group /dev/${device}priv
chmod -v $mode  /dev/${device}priv

